name: Test workflow

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
  
# jobs:
#   print-tag:
#     runs-on: ubuntu-latest
#     if:  ${{ vars.AWS_REGION == 'ap-southeast-1' }} 
#     steps:
#       - name: Print the input tag to STDOUT
#         run: echo  The tags are ${{ vars.AWS_REGION }} 

jobs:
  check-should-deploy-pulumi:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    outputs:
      should_deploy_pulumi: ${{ steps.set_should_run.outputs.should_deploy_pulumi }}
    steps:
      - name: Should run job 2 (Check condition)
        id: set_should_run
        shell: bash
        run: |
            echo "should_deploy_pulumi=${{ vars.AWS_REGION == "ap-southeast-1" }}" >> "$GITHUB_OUTPUT"

  job-2:
    runs-on: ubuntu-latest
    needs: check-should-deploy-pulumi
    environment:
      name: ${{ inputs.environment }}
    if: ${{ needs.check-should-deploy-pulumi.outputs.should_deploy_pulumi == 'true' }}
    steps:
      - name: Step 1
        run: echo "AWS_REGION is ${{ vars.AWS_REGION }}
